ccc;
ROOTPATH = fullfile(getRootDirPath(pwd, 2), "sounds");

% 预实验-阈值
pID = 101;
ISI = 3.5; % sec
nRepeat = 2;
rulesGenerator(fullfile(ROOTPATH, num2str(pID)), ...
               "rules.xlsx", ...
               pID, ...
               "start-end效应部分", ...
               "预实验阶段-阈值", ...
               "active", ...
               "SE active0", ...
               ISI, ...
               nRepeat);

% 第一阶段-阈值-1k
pID = 102;
ISI = 3.5; % sec
nRepeat = 30;
rulesGenerator(fullfile(ROOTPATH, num2str(pID)), ...
               "rules.xlsx", ...
               pID, ...
               "start-end效应部分", ...
               "第一阶段-阈值-1k", ...
               "active", ...
               "SE active1", ...
               ISI, ...
               nRepeat);

% 第二阶段-阈值-xk
pID = 103;
ISI = 3.5; % sec
nRepeat = 30;
rulesGenerator(fullfile(ROOTPATH, num2str(pID)), ...
               "rules.xlsx", ...
               pID, ...
               "start-end效应部分", ...
               "第一阶段-阈值-xk", ...
               "active", ...
               "SE active2", ...
               ISI, ...
               nRepeat);

% 第三阶段-位置
pID = 104;
ISI = 3.5; % sec
nRepeat = 30;
rulesGenerator(fullfile(ROOTPATH, num2str(pID)), ...
               "rules.xlsx", ...
               pID, ...
               "start-end效应部分", ...
               "第三阶段-位置", ...
               "active", ...
               "SE active3", ...
               ISI, ...
               nRepeat);