ccc;
mfilepath = fileparts(mfilename("fullpath"));
ROOTPATH = fullfile(getRootDirPath(mfilepath, 2), "sounds");

% 预实验-阈值
pID = 101;
ISI = 4; % sec
nRepeat = 2;
rulesGenerator(fullfile(ROOTPATH, num2str(pID)), ...
               fullfile(mfilepath, "rules_SE.xlsx"), ...
               pID, ...
               "start-end效应部分", ...
               "预实验阶段-阈值", ...
               "active", ...
               "SE active0", ...
               ISI, ...
               nRepeat, ...
               [], ...
               @seEffectThProcessFcn);

% 第一阶段-阈值-1k
pID = 102;
ISI = 3; % sec
nRepeat = 25;
rulesGenerator(fullfile(ROOTPATH, num2str(pID)), ...
               fullfile(mfilepath, "rules_SE.xlsx"), ...
               pID, ...
               "start-end效应部分", ...
               "第一阶段-阈值-1k", ...
               "active", ...
               "SE active1", ...
               ISI, ...
               nRepeat, ...
               [], ...
               @seEffectThProcessFcn);

% 第二阶段-阈值-xk
pID = 103;
ISI = 3; % sec
nRepeat = 25;
rulesGenerator(fullfile(ROOTPATH, num2str(pID)), ...
               fullfile(mfilepath, "rules_SE.xlsx"), ...
               pID, ...
               "start-end效应部分", ...
               "第一阶段-阈值-xk", ...
               "active", ...
               "SE active2", ...
               ISI, ...
               nRepeat, ...
               [], ...
               @seEffectThProcessFcn);

% 第三阶段-位置
pID = 104;
ISI = 3; % sec
nRepeat = 30;
rulesGenerator(fullfile(ROOTPATH, num2str(pID)), ...
               fullfile(mfilepath, "rules_SE.xlsx"), ...
               pID, ...
               "start-end效应部分", ...
               "第三阶段-位置", ...
               "active", ...
               "SE active3", ...
               ISI, ...
               nRepeat);