ccc;
mfilepath = fileparts(mfilename("fullpath"));
ROOTPATH = fullfile(getRootDirPath(mfilepath, 2), "sounds");

% 阶段1-插入，证明是时间整合信号
pID = 111;
ITI = 4; % sec
nRepeat = 40;
rulesGenerator(fullfile(ROOTPATH, num2str(pID)), ...
               fullfile(mfilepath, "rules_TM.xlsx"), ...
               pID, ...
               "时间绑定部分", ...
               "第一阶段-插入", ...
               "passive", ...
               "TM insert", ...
               ITI, ...
               nRepeat, ...
               "forceOpt", "on");

% 阶段2-variance
pID = 112;
ITI = 4; % sec
nRepeat = 40;
rulesGenerator(fullfile(ROOTPATH, num2str(pID)), ...
               fullfile(mfilepath, "rules_TM.xlsx"), ...
               pID, ...
               "时间绑定部分", ...
               "第二阶段-离散度", ...
               "passive", ...
               "TM variance", ...
               ITI, ...
               nRepeat, ...
               "forceOpt", "on");

% 阶段3-click train与tone比较
pID = 113;
ITI = 4; % sec
nRepeat = 40;
rulesGenerator(fullfile(ROOTPATH, num2str(pID)), ...
               fullfile(mfilepath, "rules_TM.xlsx"), ...
               pID, ...
               "时间绑定部分", ...
               "第三阶段-纯音比较", ...
               "passive", ...
               "TM tone compairson", ...
               ITI, ...
               nRepeat, ...
               "forceOpt", "on");